version: '2'

services:

  wordpress:
    image: wordpress:4.6.0-apache
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb:10.1.16
    environment:
      MYSQL_ROOT_PASSWORD: example
